spring.application.name=${APPLICATION_NAME:account-service}
server.port=${SERVER_PORT:9002}

############### Eureka client configuration ###################
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

############### MySQL Database Configuration ##################
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=${MYSQL_DRIVER_NAME:com.mysql.cj.jdbc.Driver}

################# Hibernate Configuration ####################
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${HIBERNATE_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

################# Commonlib Configuration ##################
commonlib.service.environment=${SERVICE_ENVIRONMENT:dev}
commonlib.service.name=${SERVICE_NAME:account-service}